## Optimization Assignment: Ad Revenue Maximization

### Problem Context
A new search engine plans to generate revenue by displaying advertisements on personal blogs linked to its site. Companies A, B, and C have decided to advertise only for the following four keywords: "market", "shopping", "retail", and "cheapness". Each company has specified the maximum number of sites it can handle and is willing to pay per ad click based on the keyword.

### Expected Search Volumes and Payment Rates

#### Expected Search Counts:
- **Market**: 35,000 searches
- **Shopping**: 25,000 searches
- **Retail**: 15,000 searches
- **Cheapness**: 5,000 searches

#### Payment Rates per Click (in units):
| Company | Market | Shopping | Retail | Cheapness |
|---------|--------|----------|--------|-----------|
| **A**   | 2      | 3        | 11     | 7         |
| **B**   | 1      | 2        | 6      | 1         |
| **C**   | 5      | 8        | 15     | 9         |

#### Capacity Constraints:
- **Company A**: Can handle up to 6,000 sites
- **Company B**: Can handle up to 2,000 sites
- **Company C**: Can handle up to 9,000 sites

### Objective
Your task is to maximize the total revenue generated from these ad clicks. Assume that 20% of the searches result in an ad click.

### Assignment Instructions
1. Formulate this problem as a linear programming model.
2. Implement the model in Python using `scipy.optimize.linprog`.
3. Determine the optimal number of ad displays per keyword for each company.
4. Calculate and report the total potential revenue.

### Notes
- Consider the constraints given by each company's capacity and the expected number of ad clicks per keyword.
- Your solution should explicitly state the decision variables, the objective function, and the constraints.


In [1]:
import numpy as np
from scipy.optimize import linprog

# Cost matrix representing negative revenue per ad click for maximization
costs = np.array([
    [-2, -3, -11, -7],   # Company A costs for Market, Shopping, Retail, Cheapness
    [-1, -2, -6, -1],    # Company B costs
    [-5, -8, -15, -9]    # Company C costs
])

# Supply limits for each company
supply = np.array([6000, 2000, 9000])

# Demand based on expected keyword clicks (20% of total searches)
demand = np.array([
    0.2 * 35000,  # Market
    0.2 * 25000,  # Shopping
    0.2 * 15000,  # Retail
    0.2 * 5000    # Cheapness
])

# Reshape cost matrix into a vector for optimization
c = costs.flatten()

# Inequality constraints for supply (companies can use less than or equal to their capacity)
A_ub = np.zeros((3, 12))  # 3 companies and 12 decision variables (3 companies * 4 keywords)
for i in range(3):
    A_ub[i, i*4:(i+1)*4] = 1

b_ub = supply

# Equality constraints for demand (each keyword must meet exact demand)
A_eq = np.zeros((4, 12))  # 4 keywords and 12 decision variables
for j in range(4):
    A_eq[j, j::4] = 1

b_eq = demand

# Bounds for each variable (ad displays), ensuring all values are non-negative
bounds = [(0, None)] * 12

# Solve the linear programming problem using the 'highs' method
result = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

# Extract the optimal number of ad displays if the solution is successful
if result.success:
    optimal_shares = result.x.reshape(3, 4)
    print("Optimal ad displays per company and keyword:")
    print(optimal_shares)
    print(f"Maximum revenue: ${-result.fun}")
else:
    print("Failed to find a feasible solution:", result.message)


Optimal ad displays per company and keyword:
[[5000.    0.    0. 1000.]
 [1000.    0.    0.    0.]
 [1000. 5000. 3000.    0.]]
Maximum revenue: $108000.0
